version: '2'
services:
  app:
    build:
        context: ./
        dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
        - ./:/var/www
    environment:
        - "DB_PORT=3306"
        - "DB_HOST=database"
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80
  database: # set up mysql container
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=academy"
    ports:
      - "33061:3306"
